apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-service-config-map
  namespace: default
data:
  CONFIG_SERVER_HOST: "config-server"
  MONGO_DB_HOST: "mongodb"
  MONGO_DB_PORT: "27017"
  DISCOVERY_SERVICE_HOST: "discovery-service"
  ZIPKIN_HOST: "zipkin"

---

apiVersion: v1
kind: Secret
metadata:
  name: customer-service-secret
  namespace: default
data:
  MONGO_DB_PASSWORD: "bGpPN053VnZtVg=="

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
        - name: customer-service
          image: customer-service:3.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: log-volume
              mountPath: /logs
          ports:
            - containerPort: 8002
          env:
            - name: CONFIG_SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  name: customer-service-config-map
                  key: CONFIG_SERVER_HOST
            - name: MONGO_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: customer-service-config-map
                  key: MONGO_DB_HOST
            - name: DISCOVERY_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: customer-service-config-map
                  key: DISCOVERY_SERVICE_HOST
            - name: ZIPKIN_HOST
              valueFrom:
                configMapKeyRef:
                  name: customer-service-config-map
                  key: ZIPKIN_HOST
            - name: MONGO_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: customer-service-config-map
                  key: MONGO_DB_PORT
            - name: MONGO_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: customer-service-secret
                  key: MONGO_DB_PASSWORD

      volumes:
        - name: log-volume
          emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: customer-service
spec:
  selector:
    app: customer-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8002
