apiVersion: v1
kind: ConfigMap
metadata:
  name: discovery-service-config-map
  namespace: default
data:
  CONFIG_SERVER_HOST: "config-server"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      containers:
        - name: discovery-service
          image: discovery-service:1.2
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: log-volume
              mountPath: /logs
          ports:
            - containerPort: 8761
          env:
            - name: CONFIG_SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  name: discovery-service-config-map
                  key: CONFIG_SERVER_HOST
      volumes:
        - name: log-volume
          emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: discovery-service
spec:
  selector:
    app: discovery-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8761
