apiVersion: v1
kind: ConfigMap
metadata:
  name: config-server-config-map
  namespace: default
data:
  DISCOVERY_SERVICE_HOST: "discovery-service"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: config-server:1.5
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: log-volume
              mountPath: /logs
          ports:
            - containerPort: 8888
          env:
            - name: DISCOVERY_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: config-server-config-map
                  key: DISCOVERY_SERVICE_HOST
      volumes:
        - name: log-volume
          emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: config-server
spec:
  selector:
    app: config-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
