apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-service-config-map
  namespace: default
data:
  CONFIG_SERVER_HOST: "config-server"
  DISCOVERY_SERVICE_HOST: "discovery-service"
  ZIPKIN_HOST: "zipkin"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: gateway-service:1.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: log-volume
              mountPath: /logs
          ports:
            - containerPort: 8000
          env:
            - name: DISCOVERY_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: gateway-service-config-map
                  key: DISCOVERY_SERVICE_HOST
            - name: ZIPKIN_HOST
              valueFrom:
                configMapKeyRef:
                  name: gateway-service-config-map
                  key: ZIPKIN_HOST
            - name: CONFIG_SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  name: gateway-service-config-map
                  key: CONFIG_SERVER_HOST
      volumes:
        - name: log-volume
          emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
